# history
HISTSIZE=100000
HISTFILESIZE=100000
HISTFILE=~/.hist/bash_history

. ~/dotfiles/common/bash/colors

# prompt
PS1="${txtred}\u${txtwht}@${txtblu}\h ${txtylw}\w ${txtrst}% "

. ${DOTFILES_DIR}/profile/profile
. ${DOTFILES_DIR}/profile/aliases
