. ~/dotfiles/rhel/bash/bashrc
#
# Get CIMS defaults
#
if [ -r /usr/local/lib/.system.bashrc ] ; then
    . /usr/local/lib/.system.bashrc
fi

# Make individual customizations, such as aliases, below.

