. ~/dotfiles/rhel/bash/bashrc

BASH_PS1="$PS1"
# Get CIMS defaults
#
if [ -r /usr/local/lib/.system.bashrc ] ; then
    . /usr/local/lib/.system.bashrc
fi

# Make individual customizations, such as aliases, below.
PS1="$BASH_PS1"

#module load python-2.7
PATH=/usr/local/pkg/anaconda/2.1.0/bin:$PATH
